/* Dirección visual: taller técnico editorial. Se conservan las funciones del sitio original mediante barra de accesos, ventanas modales y acciones conectadas. */
import { useEffect, useState } from "react";
import { ArrowUpRight, Camera, Check, ChevronDown, ChevronLeft, ChevronRight, Gauge, Home as HomeIcon, Menu, MessageCircle, Radio, Search, ShieldCheck, ShoppingBag, Sun, Wrench, X, Zap } from "lucide-react";

const WHATSAPP = "https://wa.me/573118184977";
const FACEBOOK_URL = "https://www.facebook.com/share/1Bzzt7CMGD/";
const FORMULARIO_URL = "https://docs.google.com/forms/d/e/1FAIpQLSdYS5pkr1U-aF7SVhIUqjDVMaM_Ky_qvg2ogfilJKW2eFeGCg/viewform";
const waService = `${WHATSAPP}?text=${encodeURIComponent("Hola, necesito un servicio técnico")}`;

const services = [
  { code: "OT-01 · HARDWARE", icon: "▣", title: "Computadores", desc: "Mantenimiento preventivo y correctivo, limpieza interna, formateo, software y recuperación de archivos.", tags: ["Sobremesa", "Portátiles", "Diagnóstico"], image: "/manus-storage/wijitech-service-support_3be28dd9.jpg", menu: ["Limpieza interna y cambio de pasta térmica", "Formateo e instalación de software", "Recuperación y respaldo de archivos"] },
  { code: "OT-02 · IMPRESIÓN", icon: "▤", title: "Impresoras", desc: "Mantenimiento, configuración y reparación de impresoras láser, de tinta y multifuncionales.", tags: ["Láser", "Tinta", "Wi-Fi"], image: "/manus-storage/wijitech-service-printers_2b2a20c0.jpg", menu: ["Limpieza de cabezales y rodillos", "Cambio de tóner o cartuchos", "Configuración Wi-Fi y escáner"] },
  { code: "OT-03 · SEGURIDAD", icon: "◉", title: "Cámaras IP / análogas", desc: "Instalación y mantenimiento de videovigilancia IP, Wi-Fi y análoga, con acceso remoto.", tags: ["IP", "Wi-Fi", "DVR/NVR"], image: "/manus-storage/wijitech-service-security-cameras_e30568e5.jpg", menu: ["Estudio de puntos ciegos y montaje", "Configuración de DVR/NVR", "Visualización desde celular y alertas"] },
  { code: "OT-04 · REDES", icon: "⌁", title: "Conexiones punto a punto", desc: "Enlaces inalámbricos para conectar edificios, fincas o locales sin cableado físico.", tags: ["Antenas", "Largo alcance", "Wi-Fi"], menu: ["Verificación de línea de vista", "Montaje, alineación y ajuste", "Internet para fincas y bodegas"] },
  { code: "OT-05 · SOPORTE", icon: "⌘", title: "Soporte técnico general", desc: "Redes domésticas, eliminación de virus, respaldo de información y asesoría en compra de equipos.", tags: ["Redes", "Seguridad", "Asesoría"], menu: ["Configuración de router e impresoras", "Eliminación de virus y respaldo", "Recomendación de equipos"] },
  { code: "OT-06 · INSTALACIÓN", icon: "⊞", title: "Cableado estructurado", desc: "Tendido de cable de red, ponchado de puntos, organización de racks y certificación básica.", tags: ["UTP", "Racks", "Puntos de red"], image: "/manus-storage/wijitech-service-cabling_f714ca8b.jpg", menu: ["Cableado UTP Cat5e/6", "Ponchado RJ45 y pruebas de continuidad", "Organización y etiquetado de rack"] },
  { code: "OT-07 · ENERGÍA", icon: "◌", title: "Paneles solares para hogares", desc: "Diseño e instalación de sistemas solares residenciales para reducir consumo y ganar autonomía energética.", tags: ["Hogar", "Ahorro", "Energía"], image: "/manus-storage/wijitech-service-solar_76470fbd.jpg", menu: ["Evaluación del consumo y el techo", "Instalación de paneles e inversor", "Puesta en marcha y orientación de uso"] },
  { code: "OT-08 · HOGAR INTELIGENTE", icon: "⌂", title: "Automatización de hogares", desc: "Controla iluminación, seguridad y dispositivos desde rutinas simples y fáciles de usar.", tags: ["Iluminación", "Seguridad", "Control"], image: "/manus-storage/wijitech-service-home-automation_0f3eb0cc.jpg", menu: ["Diseño de escenas y rutinas", "Configuración de sensores y cámaras", "Integración con asistentes y celular"] },
  { code: "OT-09 · SATELITAL", icon: "◒", title: "Instalación de Starlink", desc: "Montaje, orientación y configuración de tu conexión satelital para aprovechar mejor la señal.", tags: ["Montaje", "Orientación", "Configuración"], image: "/manus-storage/wijitech-service-starlink_4adb27b9.jpg", menu: ["Revisión del punto de instalación", "Montaje y orientación de antena", "Configuración de red y pruebas"] },
];

const courses = [
  { icon: "▣", title: "Técnico en Sistemas", level: "Básico a Intermedio", duration: "Año y medio", desc: "Fundamentos de hardware, software, redes y mantenimiento de computadores.", tags: ["Hardware", "Software", "Redes"], modules: ["Fundamentos de Hardware", "Sistemas Operativos", "Redes y Conectividad", "Mantenimiento y Soporte"] },
  { icon: "◌", title: "Inversiones y Finanzas", level: "Intermedio", duration: "40 horas", desc: "Conceptos de inversión, ahorro, presupuestos y planificación financiera.", tags: ["Finanzas", "Inversiones", "Ahorro"], modules: ["Fundamentos Financieros", "Instrumentos de Inversión", "Planificación Financiera", "Análisis de Inversiones"] },
  { icon: "⌬", title: "Inteligencia Artificial", level: "Intermedio", duration: "40 horas", desc: "Fundamentos de IA, machine learning y deep learning con aplicaciones prácticas.", tags: ["IA", "Machine Learning", "Python"], modules: ["Fundamentos de IA", "Machine Learning", "Deep Learning", "Aplicaciones Prácticas"] },
  { icon: "◇", title: "Validación de Bachillerato", level: "Todos los niveles", duration: "40 horas por grado", desc: "Programa completo de validación desde 6° hasta 11°, con todas las materias.", tags: ["Bachillerato", "Validación", "Certificación"], modules: ["6° y 7° grado", "8° y 9° grado", "10° grado", "11° grado"] },
];

const solarLoads = [
  { key: "nevera", name: "Nevera", watts: 150, defaultHours: 8, note: "consumo promedio" },
  { key: "televisor", name: "Televisor", watts: 100, defaultHours: 4, note: "por unidad" },
  { key: "iluminacion", name: "Iluminación LED", watts: 60, defaultHours: 5, note: "varias lámparas" },
  { key: "computador", name: "Computador", watts: 120, defaultHours: 6, note: "por equipo" },
  { key: "lavadora", name: "Lavadora", watts: 500, defaultHours: 1, note: "uso diario" },
  { key: "router", name: "Router / Wi-Fi", watts: 15, defaultHours: 24, note: "encendido" },
  { key: "microondas", name: "Microondas", watts: 1200, defaultHours: 0.3, note: "uso diario" },
  { key: "otros", name: "Otros equipos", watts: 200, defaultHours: 2, note: "estimación adicional" },
];

const galleryProjects = [
  { title: "Energía solar residencial", category: "Energía", image: "/manus-storage/wijitech-gallery-solar_c5977979.jpg", detail: "Instalación residencial y acompañamiento inicial para aprovechar mejor el consumo del hogar." },
  { title: "Seguridad para el hogar", category: "Seguridad", image: "/manus-storage/wijitech-gallery-security_3c684304.jpg", detail: "Montaje y configuración de cámaras para cuidar accesos y zonas comunes." },
  { title: "Red ordenada y confiable", category: "Conectividad", image: "/manus-storage/wijitech-gallery-network_c3b4bdd3.jpg", detail: "Organización de rack, cableado y puntos de red para hogares y negocios." },
  { title: "Hogar automatizado", category: "Automatización", image: "/manus-storage/wijitech-gallery-automation_858cc059.jpg", detail: "Escenas y dispositivos conectados para controlar iluminación y seguridad." },
];

const products = [
  { id: 1, cat: "camaras", name: "Cámara Wi-Fi solar 1080p", price: "$41.891 COP", badge: "Referencia ML", specs: ["1080p", "Lente dual", "Solar"], desc: "Cámara inalámbrica para exterior con visión amplia y alimentación solar.", image: "/manus-storage/wijitech-product-camera-kit_15a36fa3.jpg" },
  { id: 2, cat: "camaras", name: "Kit de 2 cámaras IP Wi-Fi 6MP", price: "$149.900 COP", badge: "Más consultado", specs: ["6MP", "Doble lente", "App móvil"], desc: "Kit para vigilancia residencial con alerta y visualización remota.", image: "/manus-storage/wijitech-product-camera-kit_15a36fa3.jpg" },
  { id: 3, cat: "camaras", name: "Cámara domo inteligente 5MP", price: "$179.212 COP", badge: "Referencia ML", specs: ["5MP", "Domo", "Exterior"], desc: "Formato discreto para controlar entradas, patios y zonas comunes.", image: "/manus-storage/wijitech-product-camera-kit_15a36fa3.jpg" },
  { id: 4, cat: "camaras", name: "Cámara IP Wi-Fi 2MP Interior", price: "$95.000 COP", badge: "En Stock", specs: ["2MP", "Wi-Fi", "Visión nocturna"], desc: "Visión nocturna, audio bidireccional y app móvil.", image: "/manus-storage/wijitech-product-camera-kit_15a36fa3.jpg" },
  { id: 5, cat: "ram", name: "Memoria RAM Samsung DDR5 8GB 5600", price: "$399.900 COP", badge: "Referencia ML", specs: ["8GB", "DDR5", "5600 MT/s"], desc: "Módulo para portátil compatible según equipo y placa.", image: "/manus-storage/wijitech-product-ram-kit_e0d68a0f.jpg" },
  { id: 6, cat: "ram", name: "Memoria RAM Crucial DDR4 16GB 2666", price: "$326.731 COP", badge: "Referencia ML", specs: ["16GB", "DDR4", "2666 MHz"], desc: "Capacidad para mejorar multitarea en portátiles compatibles.", image: "/manus-storage/wijitech-product-ram-kit_e0d68a0f.jpg" },
  { id: 7, cat: "ram", name: "Kit RAM DDR4 16GB (2×8GB) 3200", price: "Desde $250.000 COP", badge: "Consultar", specs: ["16GB", "2×8GB", "3200 MHz"], desc: "Kit de doble canal; confirma compatibilidad y marca antes de comprar.", image: "/manus-storage/wijitech-product-ram-kit_e0d68a0f.jpg" },
  { id: 8, cat: "almacenamiento", name: "SSD Crucial T500 500GB NVMe", price: "$1.260.640 COP", badge: "Referencia ML", specs: ["500GB", "NVMe", "PCIe Gen 4"], desc: "Unidad M.2 de alto rendimiento para equipos compatibles.", image: "/manus-storage/wijitech-product-ssd_7638a5d3.jpg" },
  { id: 9, cat: "almacenamiento", name: "SSD NVMe Acer Predator GM7 2TB", price: "Consultar precio", badge: "Disponibilidad", specs: ["2TB", "NVMe", "PCIe Gen 4"], desc: "Almacenamiento rápido para trabajo, creación y videojuegos.", image: "/manus-storage/wijitech-product-ssd_7638a5d3.jpg" },
  { id: 10, cat: "almacenamiento", name: "SSD Crucial T710 4TB NVMe", price: "$3.426.301 COP", badge: "Referencia ML", specs: ["4TB", "NVMe", "PCIe Gen 5"], desc: "Gran capacidad y velocidad para estaciones de trabajo compatibles.", image: "/manus-storage/wijitech-product-ssd_7638a5d3.jpg" },
  { id: 11, cat: "almacenamiento", name: "SSD SATA 480GB", price: "$155.000 COP", badge: "En Stock", specs: ["480GB", "SATA III", "540MB/s"], desc: "Acelera equipos lentos e incluye opción de clonación del disco.", image: "/manus-storage/wijitech-product-hard-drive_ed7ec0b7.jpg" },
  { id: 12, cat: "redes", name: "Kit de red Wi-Fi para hogar", price: "Desde $120.000 COP", badge: "Consultar", specs: ["Router", "Wi-Fi", "Configuración"], desc: "Router y accesorios para ampliar y ordenar la red doméstica.", image: "/manus-storage/wijitech-product-network-kit_9732ff86.jpg" },
  { id: 13, cat: "redes", name: "Kit de cableado Ethernet Cat6", price: "Desde $180.000 COP", badge: "Consultar", specs: ["Cat6", "RJ45", "Instalación"], desc: "Materiales y conectores para un punto de red confiable.", image: "/manus-storage/wijitech-product-network-kit_9732ff86.jpg" },
  { id: 14, cat: "accesorios", name: "Carcasa externa USB 3.0 SATA", price: "Desde $35.000 COP", badge: "Consultar", specs: ["2.5\"", "USB 3.0", "HDD/SSD"], desc: "Convierte un disco interno en una unidad portátil.", image: "/manus-storage/wijitech-product-hard-drive_ed7ec0b7.jpg" },
];

type Modal = "servicios" | "tienda" | "cursos" | "cobertura" | "contacto" | "solar" | "galeria" | null;
const panelOrder: Exclude<Modal, null>[] = ["servicios", "tienda", "cursos", "cobertura", "solar", "galeria", "contacto"];
const panelLabels: Record<Exclude<Modal, null>, string> = { servicios: "Servicios", tienda: "Tienda", cursos: "Cursos y matrículas", cobertura: "Cobertura y test", solar: "Calculador solar", galeria: "Galería de proyectos", contacto: "Contacto" };
type SignalState = "idle" | "testing" | "bad" | "regular" | "good";
function getSignal(speed: number) { return speed < 10 ? { state: "bad" as SignalState, label: "Señal mala", copy: "La conexión puede presentar cortes. Conviene revisar cobertura, router o enlace contratado.", color: "#a95545" } : speed < 50 ? { state: "regular" as SignalState, label: "Señal regular", copy: "Adecuada para navegación y trabajo ligero. Una optimización de red podría mejorarla.", color: "#b2874d" } : { state: "good" as SignalState, label: "Señal buena", copy: "Base sólida para videollamadas, streaming y varios dispositivos conectados.", color: "#607d68" }; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [modal, setModal] = useState<Modal>(null);
  const [openService, setOpenService] = useState<number | null>(null);
  const [course, setCourse] = useState<(typeof courses)[number] | null>(null);
  const [shopCat, setShopCat] = useState("todos");
  const [searchTerm, setSearchTerm] = useState("");
  const [signal, setSignal] = useState<SignalState>("idle");
  const [speed, setSpeed] = useState<number | null>(null);
  const [testProgress, setTestProgress] = useState(0);
  const [testPhase, setTestPhase] = useState("Listo para medir");
  const [ping, setPing] = useState<number | null>(null);
  const [upload, setUpload] = useState<number | null>(null);
  const [formSent, setFormSent] = useState(false);
  const [solarActive, setSolarActive] = useState<Record<string, boolean>>({ nevera: true, televisor: true, iluminacion: true, computador: true, router: true });
  const [solarHours, setSolarHours] = useState<Record<string, number>>(() => Object.fromEntries(solarLoads.map((load) => [load.key, load.defaultHours])));
  const [solarResult, setSolarResult] = useState<{ daily: number; recommended: number; panels: number; monthlySavings: number } | null>(null);
  const [solarTariff, setSolarTariff] = useState(900);
  const [galleryCategory, setGalleryCategory] = useState("Todos");
  const [galleryIndex, setGalleryIndex] = useState(0);
  const [galleryOpen, setGalleryOpen] = useState(false);

  useEffect(() => { document.body.style.overflow = modal || galleryOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [modal, galleryOpen]);
  useEffect(() => { if (signal !== "testing") return; const timer = window.setInterval(() => setTestProgress((current) => { const next = Math.min(92, current + 3); setTestPhase(next < 30 ? "Buscando servidor cercano" : next < 65 ? "Midiendo descarga" : "Analizando estabilidad"); return next; }), 110); return () => window.clearInterval(timer); }, [signal]);
  const open = (name: Modal) => { setModal(name); setMenuOpen(false); setCourse(null); setOpenService(null); setFormSent(false); };
  const movePanel = (direction: -1 | 1) => { if (!modal) return; const nextIndex = (panelOrder.indexOf(modal) + direction + panelOrder.length) % panelOrder.length; open(panelOrder[nextIndex]); };
  const goHome = () => { setModal(null); setMenuOpen(false); window.setTimeout(() => document.getElementById("inicio")?.scrollIntoView({ behavior: "smooth" }), 0); };
  const calculateSolar = () => { const daily = solarLoads.reduce((sum, load) => sum + (solarActive[load.key] ? load.watts * (solarHours[load.key] ?? 0) / 1000 : 0), 0); const withReserve = daily * 1.25; const panels = Math.max(1, Math.ceil(withReserve / (0.45 * 4.5))); const monthlySavings = daily * 30 * Math.max(0, solarTariff); setSolarResult({ daily: Number(daily.toFixed(1)), recommended: Number(withReserve.toFixed(1)), panels, monthlySavings: Math.round(monthlySavings) }); };
  const runSpeedTest = async () => { setSignal("testing"); setSpeed(null); setPing(null); setUpload(null); setTestProgress(4); setTestPhase("Iniciando medición"); try { const pingSamples: number[] = []; for (let i = 0; i < 3; i += 1) { const pingStart = performance.now(); await fetch(`https://speed.cloudflare.com/__down?bytes=10000&cacheBust=${Date.now()}-${i}`, { cache: "no-store" }); pingSamples.push(performance.now() - pingStart); } const measuredPing = Math.max(1, Math.round(pingSamples.reduce((sum, value) => sum + value, 0) / pingSamples.length)); setPing(measuredPing); setTestProgress(28); setTestPhase("Midiendo descarga"); const downStart = performance.now(); const response = await fetch(`https://speed.cloudflare.com/__down?bytes=1000000&cacheBust=${Date.now()}`, { cache: "no-store" }); const data = await response.arrayBuffer(); const downSeconds = (performance.now() - downStart) / 1000; const measured = Math.max(.5, Math.round(data.byteLength * 8 / downSeconds / 1000000)); setSpeed(measured); setTestProgress(63); setTestPhase("Midiendo subida"); const uploadBytes = 250000; const uploadStart = performance.now(); await fetch(`https://speed.cloudflare.com/__up?cacheBust=${Date.now()}`, { method: "POST", body: new Uint8Array(uploadBytes), cache: "no-store" }); const uploadSeconds = (performance.now() - uploadStart) / 1000; const measuredUpload = Math.max(.5, Math.round(uploadBytes * 8 / uploadSeconds / 1000000)); setUpload(measuredUpload); setTestProgress(92); setTestPhase("Analizando estabilidad"); await new Promise((resolve) => window.setTimeout(resolve, 450)); setTestProgress(100); setTestPhase("Medición completa"); setSignal(getSignal(measured).state); } catch { const fallback = Math.round((navigator as Navigator & { connection?: { downlink?: number } }).connection?.downlink ?? 18); setSpeed(fallback); setPing( typeof navigator !== "undefined" && "connection" in navigator ? 24 : null); setUpload(Math.max(1, Math.round(fallback * .35))); setTestProgress(100); setTestPhase("Medición completa"); setSignal(getSignal(fallback).state); } };
  const result = speed === null ? null : getSignal(speed);
  const filteredGallery = galleryProjects.filter((project) => galleryCategory === "Todos" || project.category === galleryCategory);
  const activeGalleryProject = filteredGallery[galleryIndex] ?? filteredGallery[0];
  const moveGallery = (direction: -1 | 1) => { if (!filteredGallery.length) return; setGalleryIndex((current) => (current + direction + filteredGallery.length) % filteredGallery.length); };
  const filteredProducts = products.filter((p) => { const matchesCategory = shopCat === "todos" || p.cat === shopCat; const haystack = `${p.name} ${p.desc} ${p.specs.join(" ")}`.toLowerCase(); return matchesCategory && haystack.includes(searchTerm.toLowerCase().trim()); });
  const buyProduct = (name: string, price: string) => window.open(`${WHATSAPP}?text=${encodeURIComponent(`Hola, quiero cotizar el producto ${name} (${price}). ¿Podrían confirmarme disponibilidad y precio final?`)}`, "_blank");

  return <div className="site-shell">
    <div className="topline"><span>WJ / SERVICIOS TÉCNICOS</span><span>DISPONIBLES EN TU ZONA</span></div>
    <header className="site-header"><a className="brand" href="#inicio" aria-label="WijiTech, inicio"><img src="/manus-storage/wijitech-logo-oficial_7c15f95b.jpg" alt="" /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button><nav className={menuOpen ? "main-nav open" : "main-nav"} aria-label="Navegación principal"><button className="nav-tab" onClick={() => open("servicios")}><span className="nav-tab-number">01</span><Wrench size={18} /><span>Servicios</span></button><button className="nav-tab" onClick={() => open("tienda")}><span className="nav-tab-number">02</span><ShoppingBag size={18} /><span>Tienda</span></button><button className="nav-tab" onClick={() => open("cursos")}><span className="nav-tab-number">03</span><ShieldCheck size={18} /><span>Cursos</span></button><button className="nav-tab" onClick={() => open("cobertura")}><span className="nav-tab-number">04</span><Radio size={18} /><span>Cobertura</span></button><button className="nav-tab nav-tab-solar" onClick={() => open("solar")}><span className="nav-tab-number">05</span><Sun size={18} /><span>Solar</span></button><button className="nav-tab" onClick={() => open("galeria")}><span className="nav-tab-number">06</span><Camera size={18} /><span>Galería</span></button><button className="nav-tab" onClick={() => open("contacto")}><span className="nav-tab-number">07</span><MessageCircle size={18} /><span>Contacto</span></button><a className="nav-action" href={waService} target="_blank" rel="noreferrer"><span>Agendar visita</span><ArrowUpRight size={17} /></a></nav></header>
    <main>
      <section id="inicio" className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="live-dot" /> SOPORTE QUE SE NOTA</p><h1>Tecnología que<br /><em>funciona</em> en tu espacio.</h1><p className="hero-description">Mantenimiento de computadores e impresoras, seguridad, redes, energía y automatización resueltas por un equipo técnico que llega, entiende y deja todo funcionando.</p><div className="hero-actions"><a className="button button-dark" href={waService} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp</a><a className="button button-facebook" href={FACEBOOK_URL} target="_blank" rel="noreferrer"><span className="facebook-mark">f</span> Visítanos en Facebook</a><button className="text-link" onClick={() => open("servicios")}>Ver todos los servicios <ArrowUpRight size={16} /></button></div><div className="hero-note"><span>01</span><p>Atención técnica sin vueltas<br /><strong>Hogares · Negocios · Proyectos</strong></p></div></div><div className="hero-visual"><img src="/manus-storage/wijitech-hero_c70ddf75.png" alt="Casa con paneles solares y conectividad técnica" /><div className="visual-stamp"><img src="/manus-storage/wijitech-logo-oficial_7c15f95b.jpg" alt="" /><span>WJ</span><small>FIELD<br />SERVICE</small></div><div className="visual-caption"><span>01 / 04</span><span>Infraestructura para vivir mejor</span></div></div></section>
      <section className="access-strip"><div><span className="access-index">00</span><strong>ACCESOS RÁPIDOS</strong></div><button onClick={() => open("servicios")}><Wrench size={16} /> Servicios</button><button onClick={() => open("tienda")}><ShoppingBag size={16} /> Tienda</button><button onClick={() => open("cursos")}><ShieldCheck size={16} /> Matrículas</button><button onClick={() => open("cobertura")}><Radio size={16} /> Test y cobertura</button><button onClick={() => open("solar")}><Sun size={16} /> Calcula tu solar</button><button onClick={() => open("galeria")}><Camera size={16} /> Ver proyectos</button></section>
      <section id="servicios" className="services-section section-pad"><div className="section-rail"><span>02</span><span>SERVICIOS</span></div><div className="section-content"><div className="section-heading"><div><p className="eyebrow">LO QUE RESOLVEMOS</p><h2>Una visita.<br /><span>Varias soluciones.</span></h2></div><p className="section-intro">Conservamos el soporte original y sumamos energía, hogar inteligente e internet satelital.</p></div><div className="service-list">{services.slice(0, 4).map(({ title, desc, tags, code, icon }, i) => <article className="service-card" key={title}><div className="service-top"><span className="service-number">{String(i + 1).padStart(2, "0")}</span><span className="service-glyph">{icon}</span></div><div className="service-body"><h3>{title}</h3><p>{desc}</p><span className="service-detail">{tags.join(" · ")}</span></div><ArrowUpRight className="card-arrow" size={20} /><button className="service-hit" aria-label={`Ver detalles de ${title}`} onClick={() => open("servicios")} /></article>)}</div><button className="inline-more" onClick={() => open("servicios")}>Ver menú completo de servicios <ChevronRight size={15} /></button></div></section>
      <section id="diagnostico" className="diagnostic-section section-pad"><div className="section-rail light"><span>03</span><span>DIAGNÓSTICO</span></div><div className="diagnostic-grid"><div className="diagnostic-copy"><p className="eyebrow">LECTURA DE CONEXIÓN</p><h2>¿Tu internet<br /><span>está respondiendo?</span></h2><p>Haz una prueba rápida desde este dispositivo. El resultado explica si tu señal es mala, regular o buena.</p><button className="button button-amber" onClick={runSpeedTest} disabled={signal === "testing"}><Gauge size={17} />{signal === "testing" ? "Midiendo conexión…" : "Iniciar test"}</button><small className="test-disclaimer">Medición real de bajada contra Cloudflare. Puede variar según tu red.</small></div><div className={signal === "testing" ? "speed-panel is-testing" : "speed-panel"}><div className="panel-header"><span>TEST / DOWNLINK</span><span className="panel-status">{signal === "testing" ? "EN CURSO" : speed !== null ? "COMPLETO" : "LISTO"}</span></div><div className="speed-readout"><div className="speed-orbit orbit-one" /><div className="speed-orbit orbit-two" /><span className="speed-value">{speed ?? "—"}</span><span className="speed-unit">Mbps</span></div>{signal === "testing" && <div className="test-progress"><div className="test-progress-line"><span>PROGRESO</span><strong>{testProgress}%</strong></div><div className="test-progress-track"><span style={{ width: `${testProgress}%` }} /></div><div className="test-phase"><i />{testPhase}</div></div>}<div className="meter"><span style={{ width: `${Math.min(100, (speed ?? 0) / 1.5)}%`, background: result?.color ?? "#c68a4a" }} /></div><div className="metric-grid"><div><span>BAJADA</span><strong>{speed ?? "—"}<small> Mbps</small></strong></div><div><span>SUBIDA</span><strong>{upload ?? "—"}<small> Mbps</small></strong></div><div><span>LATENCIA</span><strong>{ping ?? "—"}<small> ms</small></strong></div></div>{result ? <div className="result-box" style={{ borderColor: result.color }}><div className="result-title"><span className="result-dot" style={{ background: result.color }} />{result.label}</div><p>{result.copy}</p><span className="result-threshold">Referencia: {speed! < 10 ? "menos de 10 Mbps" : speed! < 50 ? "10–49 Mbps" : "50 Mbps o más"}</span></div> : <div className="empty-result"><Zap size={18} /><span>Presiona iniciar para conocer el estado de tu señal.</span></div>}</div></div></section>
      <section id="proceso" className="process-section section-pad"><div className="section-rail"><span>04</span><span>PROCESO</span></div><div className="section-content"><div className="section-heading"><div><p className="eyebrow">ASÍ TRABAJAMOS</p><h2>Orden desde<br /><span>el primer contacto.</span></h2></div></div><div className="process-grid"><div><span>01</span><h3>Escríbenos</h3><p>Cuéntanos el problema por WhatsApp.</p></div><div><span>02</span><h3>Agendamos</h3><p>Elegimos día y hora para la visita.</p></div><div><span>03</span><h3>Diagnóstico</h3><p>Revisamos y te damos un valor claro.</p></div><div><span>04</span><h3>Servicio</h3><p>Trabajo con garantía incluida.</p></div></div></div></section>
      <section id="contacto" className="contact-section"><div><p className="eyebrow">¿LO VEMOS?</p><h2>Tu espacio puede<br /><span>funcionar mejor.</span></h2></div><button className="button button-amber" onClick={() => open("contacto")}>Abrir contacto <ArrowUpRight size={17} /></button></section>
    </main><footer><div className="brand footer-brand"><img src="/manus-storage/wijitech-logo-oficial_7c15f95b.jpg" alt="" /></div><p>Servicios técnicos a domicilio · Cursos técnicos · Validación de bachillerato</p><a className="footer-facebook" href={FACEBOOK_URL} target="_blank" rel="noreferrer">Visitar página de Facebook <ArrowUpRight size={13} /></a><p>© 2026 WijiTech</p></footer><div className="wa-float"><a href={`${WHATSAPP}?text=${encodeURIComponent("Hola, necesito ayuda")}`} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={22} /></a></div>

    {modal && <div className="modal-backdrop" role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(null); }}><div className="modal-window" role="dialog" aria-modal="true" aria-label={modal}><div className="modal-header"><div className="modal-brand"><img src="/manus-storage/wijitech-logo-oficial_7c15f95b.jpg" alt="" /><span>WIJITECH <small>/ {panelLabels[modal]}</small></span></div><button className="modal-close" onClick={() => setModal(null)} aria-label="Cerrar ventana"><X size={20} /></button></div><div className="modal-nav"><button onClick={goHome}><span>⌂</span> Inicio</button><button onClick={() => movePanel(-1)} aria-label="Panel anterior">← <span>Anterior</span></button><span className="modal-nav-current">{String(panelOrder.indexOf(modal) + 1).padStart(2, "0")} / {String(panelOrder.length).padStart(2, "0")} · {panelLabels[modal]}</span><button onClick={() => movePanel(1)} aria-label="Panel siguiente"><span>Siguiente</span> →</button></div>
      {modal === "servicios" && <div className="modal-body"><p className="eyebrow">/ orden de servicio</p><h2>Lo que reparamos e instalamos</h2><p className="modal-lead">Cada visita incluye diagnóstico, mano de obra y garantía sobre el trabajo realizado.</p><div className="modal-service-grid">{services.map((s, i) => <div className={openService === i ? "modal-service is-open" : "modal-service"} key={s.title}><div className="modal-service-visual">{s.image ? <img src={s.image} alt={`Servicio de ${s.title}`} /> : <div className="service-visual-placeholder"><span>{s.icon}</span></div>}<div className="modal-service-head"><span>{s.code}</span><span>{s.icon}</span></div></div><h3>{s.title}</h3><p>{s.desc}</p><div className="modal-tags">{s.tags.map(t => <span key={t}>{t}</span>)}</div><button className="modal-expand" onClick={() => setOpenService(openService === i ? null : i)}>{openService === i ? "Ocultar menú" : "Ver menú completo"}<ChevronDown size={14} /></button>{openService === i && <ul className="modal-menu">{s.menu.map(item => <li key={item}><Check size={13} />{item}</li>)}</ul>}</div>)}</div><div className="modal-process"><p className="eyebrow">/ proceso de atención</p><div className="modal-process-grid">{["Escríbenos", "Agendamos", "Diagnóstico", "Servicio"].map((x, i) => <div key={x}><span>0{i + 1}</span><strong>{x}</strong><p>{["Cuéntanos el problema por WhatsApp.", "Elegimos día y hora — visita a domicilio.", "Revisamos y te damos un valor claro.", "Trabajo con garantía incluida."][i]}</p></div>)}</div></div></div>}
      {modal === "tienda" && <div className="modal-body"><p className="eyebrow">/ catálogo</p><h2>Tienda</h2><p className="modal-lead">Precios de referencia consultados en Mercado Libre Colombia. Cotiza por WhatsApp para confirmar disponibilidad, vendedor, envío y precio final.</p><div className="shop-search"><Search size={17} /><input value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder="Buscar productos, categorías o especificaciones…" aria-label="Buscar productos" />{searchTerm && <button onClick={() => setSearchTerm("")} aria-label="Limpiar búsqueda"><X size={15} /></button>}</div><div className="shop-controls"><div className="shop-tabs">{[["todos", "Todos"], ["camaras", "Cámaras"], ["ram", "RAM"], ["almacenamiento", "Discos"], ["redes", "Redes"], ["accesorios", "Accesorios"], ["computadores", "Computadores"]].map(([key, label]) => <button className={shopCat === key ? "active" : ""} key={key} onClick={() => setShopCat(key)}>{label}</button>)}</div><span className="shop-count">{filteredProducts.length} resultado{filteredProducts.length === 1 ? "" : "s"}</span></div><div className="shop-grid">{filteredProducts.map(p => <div className={p.id === 1 ? "shop-card is-featured" : "shop-card"} key={p.id}><div className="shop-image">{p.image ? <img src={p.image} alt={`Imagen representativa de ${p.name}`} /> : <ShoppingBag size={30} />}</div><span className="shop-badge">{p.id === 1 ? "Más consultado" : p.badge}</span><h3>{p.name}</h3><div className="shop-specs">{p.specs.map(s => <span key={s}>{s}</span>)}</div><p>{p.desc}</p><strong>{p.price}</strong><button className="button button-dark shop-buy" onClick={() => buyProduct(p.name, p.price)}>Cotizar por WhatsApp <ArrowUpRight size={14} /></button></div>)}</div>{filteredProducts.length === 0 && <div className="shop-empty"><Search size={22} /><strong>No encontramos productos</strong><span>Prueba con otro término o cambia la categoría.</span><button onClick={() => { setSearchTerm(""); setShopCat("todos"); }}>Limpiar filtros</button></div>}<div className="shop-footer"><span>¿No encuentras lo que buscas?</span><a href={waService} target="_blank" rel="noreferrer">Escríbenos y te ayudamos a conseguirlo.</a></div></div>}
      {modal === "cursos" && <div className="modal-body"><p className="eyebrow">/ formación técnica</p><h2>Cursos y matrículas</h2><p className="modal-lead">Formación práctica en áreas de alta demanda. Selecciona un curso para ver sus módulos o matricúlate directamente.</p>{course ? <div className="course-detail"><button className="back-link" onClick={() => setCourse(null)}>← Volver a cursos</button><div className="course-detail-head"><span>{course.icon}</span><div><h3>{course.title}</h3><small>{course.level} · {course.duration}</small></div></div><p>{course.desc}</p><div className="modal-tags">{course.tags.map(t => <span key={t}>{t}</span>)}</div><div className="module-list">{course.modules.map((m, i) => <div key={m}><span>0{i + 1}</span>{m}</div>)}</div><a className="button button-amber" href={`${FORMULARIO_URL}?entry.123456789=${encodeURIComponent(course.title)}`} target="_blank" rel="noreferrer">Matricularme en este curso <ArrowUpRight size={15} /></a></div> : <div className="course-grid">{courses.map(c => <div className="course-card" key={c.title} onClick={() => setCourse(c)}><span className="course-icon">{c.icon}</span><h3>{c.title}</h3><small>{c.level} · {c.duration}</small><p>{c.desc}</p><div className="modal-tags">{c.tags.map(t => <span key={t}>{t}</span>)}</div><button onClick={(e) => { e.stopPropagation(); window.open(`${FORMULARIO_URL}?entry.123456789=${encodeURIComponent(c.title)}`, "_blank"); }} className="course-enroll">Matricúlate <ArrowUpRight size={14} /></button></div>)}</div>}</div>}
      {modal === "cobertura" && <div className="modal-body"><p className="eyebrow">/ zona de cobertura</p><h2>Atendemos a domicilio</h2><p className="modal-lead">¿No ves tu sector? Escríbenos; muchas veces también podemos cubrirlo.</p><div className="coverage-grid">{["Fosca", "Quetame", "Cáqueza", "Locales comerciales", "Oficinas pequeñas", "Fincas y veredas"].map(x => <div key={x}><Radio size={15} />{x}</div>)}</div><div className="coverage-test"><div><p className="eyebrow">/ diagnóstico de red</p><h3>¿Qué tan buena es tu conexión?</h3><p>Velocidad real de bajada y referencia de señal.</p><button className="button button-amber" onClick={runSpeedTest} disabled={signal === "testing"}><Gauge size={16} />{signal === "testing" ? "Midiendo…" : "Iniciar test"}</button></div><div className={signal === "testing" ? "mini-speed is-testing" : "mini-speed"}><strong>{speed ?? "--"}</strong><span>Mbps bajada</span>{signal === "testing" && <b className="mini-phase">{testProgress}% · {testPhase}</b>}{result && <><b style={{ color: result.color }}>{result.label}</b><small className="mini-metrics">↑ {upload ?? "--"} Mbps · {ping ?? "--"} ms</small></>}</div></div></div>}
      {modal === "solar" && <div className="modal-body solar-modal"><p className="eyebrow">/ dimensionamiento inicial</p><h2>¿Qué sistema solar necesita tu hogar?</h2><p className="modal-lead">Selecciona los equipos que utilizas y estima cuántas horas funcionan al día. Calcularemos un punto de partida para conversar con nuestro equipo.</p><div className="solar-layout"><div className="solar-load-list">{solarLoads.map((load) => <label className={solarActive[load.key] ? "solar-load is-active" : "solar-load"} key={load.key}><input type="checkbox" checked={Boolean(solarActive[load.key])} onChange={() => setSolarActive((current) => ({ ...current, [load.key]: !current[load.key] }))} /><span className="solar-check" /><span className="solar-load-copy"><strong>{load.name}</strong><small>{load.watts} W · {load.note}</small></span><span className="solar-hours"><input type="number" min="0" max="24" step="0.1" value={solarHours[load.key] ?? 0} onChange={(e) => setSolarHours((current) => ({ ...current, [load.key]: Number(e.target.value) || 0 }))} aria-label={`Horas diarias de ${load.name}`} /><small>h/día</small></span></label>)}</div><aside className="solar-summary"><span className="solar-summary-kicker">ESTIMACIÓN WJ / 01</span><Sun size={28} /><h3>Diseña tu punto de partida</h3><p>Usamos una reserva del 25% y 4,5 horas solares pico como referencia inicial.</p><label className="solar-tariff"><span>Tu tarifa eléctrica</span><div><span>$</span><input type="number" min="0" step="1" value={solarTariff} onChange={(e) => setSolarTariff(Number(e.target.value) || 0)} aria-label="Tarifa eléctrica por kilovatio hora" /><small>COP / kWh</small></div><em>Ejemplo editable: reemplázalo por el valor de tu factura.</em></label><button className="button button-amber" onClick={calculateSolar}>Calcular sistema <ArrowUpRight size={15} /></button>{solarResult && <div className="solar-result"><div><span>Consumo diario</span><strong>{solarResult.daily} <small>kWh</small></strong></div><div><span>Con reserva</span><strong>{solarResult.recommended} <small>kWh</small></strong></div><div><span>Paneles sugeridos</span><strong>{solarResult.panels} <small>de 450 W</small></strong></div><div className="solar-savings"><span>Ahorro mensual estimado</span><strong>${solarResult.monthlySavings.toLocaleString("es-CO")} <small>COP</small></strong></div><p>Resultado referencial. El número final depende del techo, orientación, sombras, baterías y hábitos de consumo.</p><a className="button button-dark" href={waService} target="_blank" rel="noreferrer">Solicitar evaluación <ArrowUpRight size={15} /></a></div>}</aside></div></div>}
      {modal === "galeria" && <div className="modal-body gallery-modal"><p className="eyebrow">/ proyectos y referencias visuales</p><h2>Así puede verse un trabajo bien resuelto.</h2><p className="modal-lead">Explora áreas de trabajo de WijiTech. Estas imágenes son representativas y se pueden sustituir por fotografías propias de tus instalaciones.</p><div className="gallery-filters">{["Todos", ...Array.from(new Set(galleryProjects.map((project) => project.category)))].map((category) => <button className={galleryCategory === category ? "active" : ""} key={category} onClick={() => { setGalleryCategory(category); setGalleryIndex(0); }}>{category}</button>)}</div><div className="gallery-grid">{filteredGallery.map((project, index) => <button className="gallery-card" key={project.title} onClick={() => { setGalleryIndex(index); setGalleryOpen(true); }}><span className="gallery-image"><img src={project.image} alt={project.title} /><span className="gallery-zoom">Ampliar</span></span><span className="gallery-card-meta"><small>{project.category}</small><strong>{project.title}</strong><em>Imagen representativa · reemplazar por foto propia</em></span></button>)}</div></div>}
      {modal === "contacto" && <div className="modal-body contact-modal"><p className="eyebrow">/ contacto directo</p><h2>Coordinemos tu visita.</h2><p className="modal-lead">Cuéntanos qué pasa y te respondemos por WhatsApp.</p>{formSent ? <div className="sent-state"><Check size={26} /><h3>Mensaje preparado</h3><p>Se abrirá WhatsApp con los datos de tu solicitud.</p><a className="button button-amber" href={waService} target="_blank" rel="noreferrer">Abrir WhatsApp <ArrowUpRight size={15} /></a></div> : <form onSubmit={(e) => { e.preventDefault(); setFormSent(true); }}><label>Nombre<input required placeholder="Tu nombre" /></label><label>¿Qué necesitas?<select defaultValue=""><option value="" disabled>Selecciona un servicio</option><option>Soporte técnico</option><option>Paneles solares</option><option>Automatización del hogar</option><option>Instalación de Starlink</option><option>Otro servicio</option></select></label><label>Cuéntanos brevemente<textarea required placeholder="Describe el problema o proyecto" rows={4} /></label><button className="button button-amber" type="submit">Preparar contacto <ArrowUpRight size={15} /></button></form>}<div className="trust-row-modal"><span><strong>Diagnóstico claro</strong> antes de cobrar</span><span><strong>Garantía</strong> en cada servicio</span><span><strong>Respuesta rápida</strong> por WhatsApp</span></div></div>}
    </div></div>}
    {galleryOpen && activeGalleryProject && <div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label={`Vista ampliada: ${activeGalleryProject.title}`} onMouseDown={(e) => { if (e.target === e.currentTarget) setGalleryOpen(false); }}><button className="gallery-lightbox-close" onClick={() => setGalleryOpen(false)} aria-label="Cerrar imagen"><X size={21} /></button><button className="gallery-arrow gallery-arrow-left" onClick={() => moveGallery(-1)} aria-label="Proyecto anterior"><ChevronLeft size={24} /></button><figure><img src={activeGalleryProject.image} alt={activeGalleryProject.title} /><figcaption><span>{activeGalleryProject.category}</span><strong>{activeGalleryProject.title}</strong><p>{activeGalleryProject.detail}</p><small>Imagen representativa · sustituir por fotografía propia del proyecto</small></figcaption></figure><button className="gallery-arrow gallery-arrow-right" onClick={() => moveGallery(1)} aria-label="Proyecto siguiente"><ChevronRight size={24} /></button></div>}
  </div>;
}
